apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-mariadb-pv-claim
  namespace: api-_BRANCH_SLUG_
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
