apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: api-mariadb-credentials
  namespace: api-_BRANCH_SLUG_
spec:
  template:
    metadata:
      name: api-mariadb-credentials
      namespace: api-_BRANCH_SLUG_
    type: Opaque
  encryptedData:
    password: AgAwSVV+4J8ptZHClJJV3daNHfrr75cLO5iyyXLVHai/8ikPaoykw0mgg/I5NM7IMy0VQhqsSF8Law9/zMfuuUUaWQY3OGi1+WiOdFpw+MpSuO5czTu8JC/9gba0cixmRT8oiWvpwcYYpl1UyyH6HhGz54+ZHdWVEJRtrjmq4XAGxDq/QX9XQbU6IJ3UOU04wb5NKE2EmkIm+WvbbvoaQFVp1DnnKUmeauWT+73ScdW9aQqt+acZFWf5kkc+lgJLPq3xpOWPNLz2RSl1xBBVcvd+y865buPkCRK4/Naj5GylRie+F7fx4TlolECdGXLWRISUM3DDZT2LXHjSsGi78Ij3At+1hWjuIwzIkfvH8hzhZ5Cr47c5f30ETVxSaHB7U/JPqbq67214FUX4CBP8iRol2fEEvfRjtvfrGVX1xFd1hDfP9h4+fQSPL+xrNWoa2oHgwl/78ZdA6ZdZMIe8asQzSAGYMUUfM+6BN55TSQrfrmAmLZJTdWQz+mpCmeAXsjJGaEEDi0BcmrCTgyCkjee81f2B0C0tw1i5HXoT4BTyxRKvvTA5BftBIWSiTTP1yEszg2vBr9JemsVNXlQPCsSbg2Fbv8AAunUsEXbmUerCi8XuKd6J0Ujis9eHiao+apDTaHw0BCyM+pueNKoJSQAfVBAOAMhFY3sMie79UvVboCq6N3Gbq065qLbhwewEe6bHNzxC
    username: AgBb8cxSctHhnr0kxfRmJ3Q62vHQhTj+s28lYchMWtqtYufngpZBn28hEnSKCl2AjdgBCuMUL30MzcIoWPOQKIxsN/9ea2TMNDoCuHgi48r9TrWjVfdH2Rm6FrOQUZcifSlVh7GQu5/aNilarPbyBK4Qa3eN8pY3kS8vdG2jvJqSs/tfopuBA5556/E1zCRzL+qPxnfIHpkWNSNP3K5qfkylTAIr4Zk+IgH/qmCXhV0ZP6x3tH5j21Eahq4hCdFb9sEio13KVOYxaLBfbznuTSdJqG7nYRxCneBodUvMa9E98pd8zEI9+aoZUtm9xHfjvCX8DZ0MzB1+r3IlCBq17udFlWVglKVIMH48yjvr6GAPMGe4Ou4Wl2bGjllEbBBcwoDowdF3GYeL7GZ1BFqCPbBR+t4g65qhqj30UgdDsYgLLAJeMDqkC87eaiY2e/EtpK+Lnrx8Ow42y3OmbvIK9rP1hTWAiVaet7SGvX8kqOqF83E8ohHp7q/c5F4HVkvWoBuKIcLooCuK0KNZ9IM083WG4tpv0KLjksStOxsahI7iF7RCKytZLzrj7dtUFNdrgg2m3AC7crUOUcAcoZ2sx0IDw4CnPbfrjdb5tghpwb4guL3enLrsZrm7okkPA5jqWB72Qmv9Nx0NAA22Ba0+kk6RA0ZuCBXZJuqbnI2a36uVjAva47KNeg0BoiYP+YTh89KBnePo
