apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-nginx
  namespace: api-_BRANCH_SLUG_
  labels:
    app: api-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-nginx
  template:
    metadata:
      labels:
        app: api-nginx
    spec:
      containers:
      - name: api-nginx
        image: docker.io/iedereenhelpt/api-nginx:_COMMIT_
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 120
          periodSeconds: 5
        volumeMounts:
          - name: nginx-cfg
            mountPath: /etc/nginx/conf.d
      volumes:
        - name: nginx-cfg
          configMap:
            name: nginx-cfg
