apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: api-nginx
  namespace: api-_BRANCH_SLUG_
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts: [_BRANCH_SLUG_.iedereenhelpt.dev]
      port:
        number: 80
        name: http
        protocol: HTTP
      tls:
        httpsRedirect: true
    - hosts: [_BRANCH_SLUG_.iedereenhelpt.dev]
      port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: iedereenhelpt-dev
        privateKey: sds
        serverCertificate: sds
