name: development

on:
  push:
    branches:
      - 'feature/**'
      - 'bugfix/**'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: docker login
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: composer install
        run: |
          docker run --rm -v $PWD:/app -w /app composer install \
            --no-progress --optimize-autoloader --ignore-platform-reqs \
            --no-suggest --no-dev
      - name: docker php build
        run: |
          docker build -t iedereenhelpt/api-php:${{ github.sha }} -f docker/php/Dockerfile .
          docker push iedereenhelpt/api-php:${{ github.sha }}
      - name: docker nginx build
        run: |
          docker build -t iedereenhelpt/api-nginx:${{ github.sha }} -f docker/nginx/Dockerfile .
          docker push iedereenhelpt/api-nginx:${{ github.sha }}
      - uses: azure/setup-kubectl@v1
        id: install
      - name: kubectl config setup
        run: |
          mkdir -p $HOME/.kube && \
          echo $KUBECTL > $HOME/.kube/config
        env:
          KUBECTL: ${{ secrets.KUBECTL }}
      - name: kubectl apply
        run: |
          cat k8s/development/namespace.yaml | \
          sed "s^_BRANCH_SLUG_^${GITHUB_REF##*/}^g" | \
          kubectl apply -f - && \
          kubectl kustomize k8s/development | \
          sed "s^_BRANCH_SLUG_^${GITHUB_REF##*/}^g" | \
          sed "s^_COMMIT_^${{ github.sha }}^g" | \
          kubectl apply -f -
