name: build

on:
  push: [tags]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: docker login
        uses: azure/container-actions/docker-login@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: |
          docker build -t iedereenhelpt/api-php:${{ github.sha }} -f docker/php/Dockerfile .
          docker push iedereenhelpt/api-php:${{ github.sha }}
      - run: |
          docker build -t iedereenhelpt/api-nginx:${{ github.sha }} -f docker/nginx/Dockerfile .
          docker push iedereenhelpt/api-nginx:${{ github.sha }}
