name: production

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: docker login
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: docker php build
        run: |
          docker build -t iedereenhelpt/api-php:${{ github.sha }} -f docker/php/Dockerfile .
          docker push iedereenhelpt/api-php:${{ github.sha }}
      - name: docker nginx build
        run: |
          docker build -t iedereenhelpt/api-nginx:${{ github.sha }} -f docker/nginx/Dockerfile .
          docker push iedereenhelpt/api-nginx:${{ github.sha }}
